name: Tests on pull

on:
  pull_request:

env:
  SERVER_SSH_USER: ${{ secrets.SERVER_SSH_USER }}
  SERVER_SSH_PRIV_KEY: ${{ secrets.SERVER_SSH_PRIV_KEY }}
  SERVER_ADDRES: ${{ secrets.SERVER_ADDRES }}
  SERVER_ADDRES_IP: ${{ secrets.SERVER_ADDRES_IP }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_CONTAINER_NAME: ${{ secrets.DOCKER_CONTAINER_NAME }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint flake8
      uses: py-actions/flake8@v2
      with:
        max-line-length: "120"
        path: "src"

    - name: Test with pytest
      run: |
        python -m unittest tests/test_app.py